- name: Run ibmcloud cli invite users
  ansible.builtin.shell: "ibmcloud account user-invite {{ item.value.email }}"
  register: ibmcli_output
  failed_when: ( ibmcli_output.rc not in [ 0, 1 ] )

- name: Output of ibmcli command
  ansible.builtin.debug:
    msg: '{{ item }}'
  loop:
    - '{{ ibmcli_output }}'
  tags: never


- name: Run govc group find
  ansible.builtin.shell: "govc sso.group.ls -search {{ item.value.role  }}"
  register: grouplookup

- name: Run govc group create
  ansible.builtin.shell: "govc sso.group.create {{ item.value.role  }}"
  when: grouplookup == ""

- block:

    - name: Run govc user find
      ansible.builtin.shell: "govc sso.user.id {{ item.value.kerberos }}"

  rescue:

    - name: Set password and domain
      ansible.builtin.set_fact: 
         my_pass: "{{ pwd_alias }}"
         domain: "{{ vcenter | urlsplit('hostname') }}"

    - name: Set subdomain
      ansible.builtin.set_fact: 
         subdomain: "{{ domain.split('.')[1:] | join('.') }}"
         #subdomain: "{{ domain | regex_replace('^.+\\.', '') }}"
         #subdomain: "{{ domain.split('.') | list | getitem(1) }}"
         #domain: "{{ 'vcenter' | regex_search('http://+)', '\\1') }}"
 
    - name: Show user password
      ansible.builtin.debug:
        msg: "vCenter to login to {{ vcenter }} login in with this info {{ item.value.kerberos }}@{{ subdomain }} user this password {{ my_pass }}     "

    - pause:
    
    - name: Run govc user create
      ansible.builtin.shell: "govc sso.user.create -f {{ item.value.first  }} -l {{ item.value.last }} -m {{ item.value.email }} -p '{{ my_pass }}' {{ item.value.kerberos }}"
    
    - name: Run govc update group
      ansible.builtin.shell: "govc sso.group.update -a {{ item.value.kerberos }} {{ item.value.role  }}"


#      govc_runner("govc sso.group.create " + newGroup)
#      govc_runner("govc sso.user.create -f '" + newFirst + "' -l '" + newLast + "' -m '" + newUserEmail + "' -p '" + newUserPassword + "' '" + newUserUsername + "'")
#      govc_runner("govc sso.group.update -a " + newUserUsername + " " + newGroup)



