- name: Run ibmcloud cli invite users
  ansible.builtin.shell: "ibmcloud account user-invite {{ item.value.email }}"
  register: ibmcli_output
  failed_when: ( ibmcli_output.rc not in [ 0, 1 ] )

- name: Output of ibmcli command
  ansible.builtin.debug:
    msg: '{{ item }}'
  loop:
    - '{{ ibmcli_output }}'
  tags: never

- name: Run govc group create
  ansible.builtin.shell: "govc sso.group.create {{ item.value.role  }}"
  ignore_errors: True

- name: Set password
  ansible.builtin.set_fact: 
     my_pass: "{{ pwd_alias }}"

- name: Show user password
  ansible.builtin.debug:
    msg: "password for {{ item.value.kerberos }} {{ my_pass }}"

- name: Run govc user create
  ansible.builtin.shell: "govc sso.user.create -f {{ item.value.first  }} -l {{ item.value.last }} -m {{ item.value.email }} -p {{ my_pass }} {{ item.value.kerberos }}"

- name: Run govc update group
  ansible.builtin.shell: "govc sso.user.update -a {{ item.value.kerberos }} {{ item.value.role  }}"


#      govc_runner("govc sso.group.create " + newGroup)
#      govc_runner("govc sso.user.create -f '" + newFirst + "' -l '" + newLast + "' -m '" + newUserEmail + "' -p '" + newUserPassword + "' '" + newUserUsername + "'")
#      govc_runner("govc sso.group.update -a " + newUserUsername + " " + newGroup)



