- hosts: localhost
  vars:
    pwd_alias: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1, length=15, override_special='#$%&().:;<=>^_{}' ) }}"
    #pwd_alias: "{{ lookup('password', '/dev/null length=15') }}"
    vcenter: "{{ lookup('ansible.builtin.env', 'GOVC_URL') }}"
    jsonVar: "{{ lookup('file', 'data.json') | from_json }}" 
    doc: ""
  tasks:

    - name: reading csv file
      community.general.read_csv:
        path: usernames.csv
        key: kerberos
      register: users

    - ansible.builtin.debug:
        msg: "{{ users }}"
      tags: never

    - ansible.builtin.debug:
        msg: "{{ item.key }}:
              {{ item.value.kerberos }},
              {{ item.value.email }},
              {{ item.value.role }},
              {{ item.value.first }},
              {{ item.value.last }},
              {{ item.value.twrole }}"
      loop: "{{ users.dict|dict2items }}"
      tags: never

    - name: Run ibmcloud login
      ansible.builtin.shell: "ibmcloud login --no-region"
      register: ibmcli_output
      failed_when: ( ibmcli_output.rc not in [ 0, 1 ] )

    - name: Create user
      include_tasks: createuser.yml
      loop: "{{ users.dict|dict2items }}"

    - name: Run ibmcloud logout
      ansible.builtin.shell: "ibmcloud logout"
      register: ibmcli_output
      failed_when: ( ibmcli_output.rc not in [ 0, 1 ] )


